spring.application.name=E-commerce_project

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/ecom
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.files.upload.folder.products=uploads/products


#stripe configurations

stripe.secret.key=need to add
stripe.publishable.key=need to add

frontend.success.url=http://localhost:5173/payment-success
frontend.cancel.url=http://localhost:5173/payment-cancel



springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs


security.jwt.secret=need` to add
security.jwt.access-token-expire-time=600000
security.jwt.refresh-token-expire-time=3600000
security.jwt.issuer=Vijay_Dev